name: example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  map_manager_mapbox:
    path: ..
  mapbox_maps_flutter: ^2.8.0
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/3d_models/
